import type { Metadata } from "next";
import "ui/styles/globals.css";
import Providers from "@/components/Providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Inter } from 'next/font/google' // 해당 폰트의 함수를 사용합니다.

const inter = Inter({ subsets: ['latin'] }) // 변수를 선언하고, 함수의 인자로 스타일을 지정합니다.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
      </head>
      <body
        className={inter.className}
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
