import type { Metadata } from "next";
import "ui/styles/globals.css";
import Providers from "@/shared/ui/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  viewport:
    "minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
};

import { Inter } from "next/font/google"; // 해당 폰트의 함수를 사용합니다.

const inter = Inter({ subsets: ["latin"] }); // 변수를 선언하고, 함수의 인자로 스타일을 지정합니다.
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </head>
      <body className={`${inter.className} h-real-screen`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
